springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    version: openapi_3_0
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: "admin"
      display-name: "管理员"
      packages-to-scan:
        - pers.lwb.controller.admin
    - group: "user"
      display-name: "用户"
      packages-to-scan:
        - pers.lwb.controller.user

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

