spring.application.name:
  sky-server

server:
  port: 8080

spring:
  #  开启 dev 配置类生效
  profiles:
    active: @runtime-profiles@
  main:
    allow-circular-references: true

  # MySQL 数据库
  datasource:
    #    druid:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}

  SERVLET:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  # Redis
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      password: ${sky.redis.password}
      database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:pers/lwb/mapper/*.xml
  type-aliases-package: pers.lwb.entity
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    pers:
      lwb:
        mapper: debug
        service: info
        controller: info

#JWT 令牌
sky:
  jwt:
    admin-secret-key: ${sky.jwt.admin-secret-key}
    admin-token-name: ${sky.jwt.admin-token-name}
    admin-ttl: ${sky.jwt.admin-ttl}
    user-secret-key: ${sky.jwt.user-secret-key}
    user-ttl: ${sky.jwt.user-ttl}
    user-token-name: ${sky.jwt.user-token-name}

# 阿里云 OSS
aliyun:
  oss:
    endpoint: ${aliyun.oss.endpoint}
    bucket-name: ${aliyun.oss.bucket-name}
    region: ${aliyun.oss.region}
    credential:
      access-key-id: ${aliyun.oss.credential.access-key-id}
      access-key-secrect: ${aliyun.oss.credential.access-key-secrect}
      ttl: ${aliyun.oss.credential.ttl}

wechat:
  appid: ${wechat.appid}
  secret: ${wechat.secret}
  mchid: ${wechat.mchid}
  mch-serial-no: ${wechat.mch-serial-no}
  private-key-file-path: ${wechat.mch-serial-no}
  api-v3-key: ${wechat.api-v3-key}
  we-chat-pay-cert-file-path: ${wechat.we-chat-pay-cert-file-path}
  notify-url: ${wechat.notify-url}
  refund-notify-url: ${wechat.refund-notify-url}

